### ISSUE TITLE
Probably a typo in readme regarding S3

### ISSUE THREAD

**Issue by misiek08** [mbrt/glassdb#59]
> More work is required for [Amazon S3](https://aws.amazon.com/s3/) which lacks request preconditions on uploads.

vs

> Requires access to object storage (the lowest latency the better) with requests preconditions (both Google GCS and AWS S3 meet the requirements).

I think in the tradeoffs you meant `Azure` :)

**Comment by danielloader** [comment]
Given all three support conditional writes now... 🤘

**Comment by misiek08** [comment]
> Posted on: Nov 25, 2024

I think someone at AWS read Hacker News topic about GlassDB, checked their 1st layer config and just removed limit for HTTP methods :D Great news to see this!

**Comment by mbrt** [comment]
Ah, that's right! It seems that finally AWS is waking up after basically all competitors started offering this years ago.
